### ISSUE TITLE
Creating relational tables

### ISSUE THREAD

**Issue by dpatti** [stripe/mosql#11]
One extension that I am looking at working on is some sort of support for many-to-many relationships. Typically you would have a table that contains the primary keys of each of the relevant rows, but in MongoDB you might use an array within a document. So I was thinking about something like this:

``` yaml
my_blog:
  posts:
    :columns:
      - _id: VARCHAR(24)
      - title: VARCHAR(150)
    :meta:
      :table: posts
      :extra_props: true
    :related:
      user_post_likes:
        - _id: VARCHAR(24)
        - users_liked[]: VARCHAR(24)
      user_post_ratings:
        - _id: VARCHAR(24)
        - ratings[].user_id: VARCHAR(24)
        - ratings[].score: INT
```

So basically it creates two relational tables, and in the first it just reads an array of ObjectIDs or strings from `users_liked`, whereas the second reads an array of subdocs containing `user_id` and `score` attributes. The `[]` indicates that a new row should be inserted for each item in the array. I don't know much about how the oplog tailer works, but there could be massive problems that I'm overlooking.

Any thoughts or feedback?
