### ISSUE TITLE
Duplicating records and tailing the oplog?

### ISSUE THREAD

**Issue by AndreaCrotti** [stripe/mosql#57]
1. Why if I run the command in this way
   
   mosql -c comments.yaml --mongo mongodb://django:django@localhost:27017/ --sql postgres://django:django@localhost/garage  -v -v -v --no-drop-tables
   
   It quits when it's done importing?
   Should it not run forever reading the oplog?
   
   Is it not possible to let it run forever tailing the oplog (until stopped)?
2. If I run the migration with a schema as below multiple times, my records get duplicated.
   
   This is maybe because I am not specifying an ID so I'm letting Postgres create new records with new ids.
   But is it not possible to make it only create new record if not there already in another way?
   
   I just want to make sure that if I have to run it twice I don't get duplicate data..

``` yaml
    alexandria:
      searchable_comment:
        :columns:
        - text: TEXT
        - status: TEXT
        - author_id:
          :source: user.user_id
          :type: INT
        - product_id: INT
        - date: TIMESTAMP

        :meta:
          :table: dp_comments_comment
```

Thanks
